import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers";
import AuthProvider from "@/context/AuthContext";
import { ThemeProvider } from "@/lib/providers/ThemeProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["600"],
});

export const metadata = {
  title: "Cake Heaven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.variable} ${spaceGrotesk.variable} min-h-full flex flex-col antialiased bg-white dark:bg-background text-black dark:text-on-background font-body-md overflow-x-hidden`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          <AuthProvider>
            <Providers>
              {children}
            </Providers>
          </AuthProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
